### ISSUE TITLE
missing ZONE triggers

### ISSUE THREAD

**Issue by deondti** [hawky358/hass_ids_hyyp#33]
I just updated to V1.8.3 and my zone triggers have dissapeared, I restarted HA twice

**Comment by hawky358** [comment]
Hello,

What do you mean by zone triggers?
What is/was the sensor name?

**Comment by deondti** [comment]
example

binary_sensor.zone_16_trigger

But every single one is missing of the zones, basic sensors are still there just not the zones trigger sensors
I have taken a screenshot of all the available sensors

![Untitled](https://github.com/user-attachments/assets/6bd384cc-3e34-4f2f-9ebd-a15f48418c01)

**Comment by hawky358** [comment]
Hello,

Yes, this is expected behaviour. You should delete those entities and replace any dependant code with the sensor attributes. (see below)

The trigger sensors were deprecated in 1.4.1 [(changelog)](https://github.com/hawky358/hass_ids_hyyp/tree/1.4.1#changelog) and replaced with trigger attributes within the zone sensors (this allowed for more information to be consolidated in the attributes). These trigger sensors were then removed in  1.6.0 [(changelog)](https://github.com/hawky358/hass_ids_hyyp/tree/1.6.0#changelog).

As mentioned, if you have any automatons or code which depends on this information, you should replace it with the relevant attribute. The detail is explained in 

- [(1.4.1)](https://github.com/hawky358/hass_ids_hyyp/tree/1.4.1#changelog) or 
- [features](https://github.com/hawky358/hass_ids_hyyp?tab=readme-ov-file#features) under _Bypass of individual zones via switch entities_

**Comment by hawky358** [comment]
Let me know if you have trouble resolving this. 
Here's an example of the attribute (Jinja template) and screenshot from the sensor.

```
{% set trigger_example = state_attr('switch.agter_deur', 'triggered') %}
{{ trigger_example }}
```
<br>
<br>
<br>



![image](https://github.com/user-attachments/assets/6a7900e6-81e8-4734-8541-1dc909681906)

**Comment by deondti** [comment]
I tried these...
I changed it to violated just to test without arming the alarm

"""
trigger: template
value_template: "{% set trigger_example = state_attr('switch.gate', 'violated') %}"
"""

and 
"""
trigger: state
entity_id:
  - switch.gate
attribute: violated
from: "false"
to: "true"
"""

but no success, my attributes are showing up under the switch just like your photo and they do change, now just to create a trigger from it

**Comment by deondti** [comment]
100% I tried visual editor with changing attributes , I had to change the default "true" to true
Working example below
"""
trigger: state
entity_id:
  - switch.gate
attribute: violated
to: true

"""

Thank you for this add on and your efforts
