### ISSUE TITLE
New 1.3 beta .... my site is deleted from the Securehome app ... 

### ISSUE THREAD

**Issue by bobstardelux** [hawky358/hass_ids_hyyp#6]

**Comment by bobstardelux** [comment]
Tried adding it again and it sends an error msg that the radio is associated with a user already .... something very broken

**Comment by hawky358** [comment]
Interesting. I've been running the 1.3.0-b1 for a week or so without issue.

The only thing that's changed with how the system interacts with the server in 1.3.0-b1 is that it polls every 30 seconds not every 60 seconds. Nothing else has changed which could influence the site. 
The integration itself makes no changes to the site it just logs in another "device"

From the error message it seems like ADT is limiting the amount of simultaneous users/devices per site.

I assume you are using ADT from the app name. I don't have access to an ADT system so I can't properly test to see how it works differently from the normal IDS implementation

You can try using 1.2.2 and see whether it changes anything (that's on 60 second poll time) or completely log out / remove the integration. Wait a few minutes so that the IDS server also times out then try on the app.

I can unfortunately not replicate this. Let me know if you can see anything with the above steps.

**Comment by hawky358** [comment]
> That would be really interesting to know 

Of course it will only show if people activated analytics in their HA installation which allows gathering of this type of information.
